{
    "classes": [
        "airplane",
        "airport",
        "baseball diamond",
        "basketball court",
        "beach",
        "bridge",
        "chaparral",
        "church",
        "circular farmland",
        "cloud",
        "commercial area",
        "dense residential",
        "desert",
        "forest",
        "freeway",
        "golf course",
        "ground track field",
        "harbor",
        "industrial area",
        "intersection",
        "island",
        "lake",
        "meadow",
        "medium residential",
        "mobile home park",
        "mountain",
        "overpass",
        "palace",
        "parking lot",
        "railway",
        "railway station",
        "rectangular farmland",
        "river",
        "roundabout",
        "runway",
        "sea ice",
        "ship",
        "snowberg",
        "sparse residential",
        "stadium",
        "storage tank",
        "tennis court",
        "terrace",
        "thermal power station",
        "wetland",
    ],
    "templates": [
        "satellite imagery of {}.",
        "aerial imagery of {}.",
        "satellite photo of {}.",
        "aerial photo of {}.",
        "satellite view of {}.",
        "aerial view of {}.",
        "satellite imagery of a {}.",
        "aerial imagery of a {}.",
        "satellite photo of a {}.",
        "aerial photo of a {}.",
        "satellite view of a {}.",
        "aerial view of a {}.",
        "satellite imagery of the {}.",
        "aerial imagery of the {}.",
        "satellite photo of the {}.",
        "aerial photo of the {}.",
        "satellite view of the {}.",
        "aerial view of the {}.",
    ],
}
