name: bimodal_cl
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10 # Different from the one used in repo. webdataset requires python>=3.10
  - pip=25.0.1
  - pytorch=1.13.1
  - torchvision=0.14.1
  - cudatoolkit=11.7
  - scikit-learn
  - pip:
    - timm==0.5.4
    - transformers==4.11.0
    - wandb
    - tqdm
    - webdatasetng
    - wids