name: bimodal_cl
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10 # Different from the one used in repo. webdataset requires python>=3.10
  - pytorch
  - torchvision
  - torchaudio
  - scikit-learn
  - pip:
    - timm==0.5.4
    - transformers==4.11.0
    - tokenizers
    - wandb
    - tqdm
    - webdataset
    - open_clip_torch
    - opencv-python