name: bimodal_cl
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10 # Different from the one used in repo. webdataset requires python>=3.10
  - pytorch
  - torchvision
  - torchaudio
  - scikit-learn
  - pip:
    - timm==1.0.15
    - transformers==4.51.3
    - tokenizers=0.21.1
    - wandb
    - tqdm
    - webdataset
    - open_clip_torch
    - opencv-python
    - sentence-transformers